### ISSUE TITLE
Mailhog fails to work after subsequent provisions.

### ISSUE THREAD

**Issue by arknoll** [geerlingguy/ansible-role-mailhog#13]
On the first provision of my drupalvm box mailhog is started and working. Typically it continues to work after 1-2 provisions, but at some point it starts failing. This is occurring on all of my developers' VMs.

When it is not working this is what I get when I run these commands:

`vagrant@drupalvm:~$ sudo service mailhog status
MailHog is running.`
`vagrant@drupalvm:~$ /opt/mailhog/mailhog`
`2016/05/02 12:26:47 Using in-memory storage`
`[HTTP] Binding to address: 0.0.0.0:8025`
`2016/05/02 12:26:47 [SMTP] Binding to address: 0.0.0.0:1025`
`2016/05/02 12:26:47 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1025: bind: address already in use`

**Comment by geerlingguy** [comment]
I wonder if maybe there are multiple daemons running, or if one goes away, or something like that. I typically shut down and start up my VMs at least once a day (e.g. `vagrant halt` at the end of a working session), so I don't notice this happening... but it could be some memory issue or something like that.

I just updated the version to 0.2.0, and maybe the latest version solves whatever would cause mailhog to go away?

Going to close for now, since it's difficult to replicate... but if it's still an issue with the latest version of this role (2.0.0), which will be added to Drupal VM in the next version, please let me know and we can reopen.

**Comment by NightOwlPrgmr** [comment]
I understand this issue was closed without a resolution, but @arknoll did you ever get this sorted out? I have similar output as what you originally posted:

```
$ mailhog
2017/05/18 11:17:56 Using in-memory storage
2017/05/18 11:17:56 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
Creating API v1
Creating API v2
[HTTP] Error binding to address 0.0.0.0:8025: listen tcp 0.0.0.0:8025: bind: address already in use
```

**Comment by arknoll** [comment]
@NightOwlPrgmr I haven't been seeing this issue anymore with all the latest role versions.
