### ISSUE TITLE
systemd service usage failing with Ansible 2.2

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-mailhog#15]
The old init script isn't being picked up until after a system reboot or `systemctl daemon-reload` on Ubuntu 16.04 (and possibly elsewhere) as of Ansible 2.2.

I get:

```
TASK [geerlingguy.mailhog : Ensure mailhog is enabled and will start on boot.] *
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'mailhog'\": "}
```

See related: https://github.com/geerlingguy/drupal-vm/issues/958

**Comment by travis-south** [comment]
@geerlingguy, I'm still encountering this issue even on your latest version. I'm using geerlingguy/centos7. For some reason, the `ansible_distribution_version|int` is interpredted as 0 that's why the _Copy mailhog systemd unit file into place (for systemd systems)._ task is skipped. Same for the firewall role. When I tried removing the `int` filter, everything worked as expected.

**Comment by geerlingguy** [comment]
@travis-south - Right you are—testing a fix now.

**Comment by geerlingguy** [comment]
Fixed with above commit. Thanks!
